GET http://localhost:8080/models


###
POST https://spring-cloudevent-function-polyglot-demo.tap-next.blah.cloud
content-Type: application/cloudevents+json

{
    "specversion" : "1.0",
    "type" : "hire",
    "source" : "https://spring.io/",
    "id" : "A234-1234-1234",
    "datacontenttype" : "application/json",
    "data": {
        "firstName": "John",
        "lastName": "Doe"
    }
}

